import type { AppData } from "../types";

// ── Published seed data ─────────────────────────────────────────────────────────
// This is the schedule everyone sees on first load (and after a data-version
// bump). It is the single source of truth for the deployed site. To publish a
// new schedule: edit the sessions/ideas below and bump DATA_VERSION in
// persistence.ts so returning visitors refresh to the new content.
export const SEED_APP_DATA: AppData = {
  semesterConfig: {
    name: "Fall 2026",
    startDate: "2026-08-24",
    endDate: "2026-12-19",
    meetingTime: "15:30",
    meetingDayOfWeek: 5,
  },
  version: 7,
  sessions: [
    {
      id: "seed-2026-09-04",
      date: "2026-09-04",
      time: "15:30",
      topic: "First Code Review of the Semester -- Discussion",
      speaker: "",
      notes: "",
      status: "completed",
    },
    {
      id: "seed-2026-09-11",
      date: "2026-09-11",
      time: "15:30",
      topic: "Thingy demo",
      speaker: "Claude Users",
      notes: "https://huggingface.co/spaces/cabouman/thingy-repository",
      status: "completed",
    },
    {
      id: "seed-2026-09-18",
      date: "2026-09-18",
      time: "15:30",
      topic: "Beam Hardening",
      speaker: "Charlie",
      notes: "",
      status: "confirmed",
    },
    {
      id: "seed-2026-09-25",
      date: "2026-09-25",
      time: "15:30",
      topic: "Computation Hardware",
      speaker: "Greg",
      notes: "A GPU profiling. Or how to think about problems with a GPU versus a CPU. ",
      status: "confirmed",
    },
    {
      id: "seed-2026-10-02",
      date: "2026-10-02",
      time: "15:30",
      topic: "20-minute research presentation",
      speaker: "Dominic",
      notes: "",
      status: "confirmed",
    },
    {
      id: "seed-2026-10-09",
      date: "2026-10-09",
      time: "15:30",
      topic: "Visit from Marcus Carlsson (Lund University) — talk or discussion TBD",
      speaker: "Marcus Carlsson",
      notes: "Former Purdue math postdoc, now a professor at Lund University, visiting on Oct 9. Format (talk vs. discussion) to be decided.",
      status: "confirmed",
    },
    {
      id: "seed-2026-10-16",
      date: "2026-10-16",
      time: "15:30",
      topic: "Job talk ",
      speaker: "Jeffrey",
      notes: "",
      status: "proposed",
    },
    {
      id: "seed-2026-10-23",
      date: "2026-10-23",
      time: "15:30",
      topic: "SPACE",
      speaker: "Harel",
      notes: "The new Nancy Grace Roman Space Telescope. ",
      status: "proposed",
    },
    {
      id: "seed-2026-10-30",
      date: "2026-10-30",
      time: "15:30",
      topic: "STORM",
      speaker: "Xiao Wang",
      notes: "Xiao's algorithm, recently nominated for the Gordon Bell Prize.",
      status: "confirmed",
    },
    {
      id: "seed-2026-11-06",
      date: "2026-11-06",
      time: "15:30",
      topic: "20-minute research presentation",
      speaker: "Mingqi",
      notes: "",
      status: "proposed",
    },
    {
      id: "seed-2026-11-13",
      date: "2026-11-13",
      time: "15:30",
      topic: "Sowmya's research talk",
      speaker: "Sowmya",
      notes: "",
      status: "proposed",
    },
    {
      id: "seed-2026-11-20",
      date: "2026-11-20",
      time: "15:30",
      topic: "20-minute research presentation",
      speaker: "JIngsong",
      notes: "",
      status: "proposed",
    },
    {
      id: "seed-2026-11-27",
      date: "2026-11-27",
      time: "15:30",
      topic: "THANKSGIVING",
      speaker: "",
      notes: "",
      status: "proposed",
    },
    {
      id: "seed-2026-12-04",
      date: "2026-12-04",
      time: "15:30",
      topic: "20-minute research presentation",
      speaker: "Ziyun",
      notes: "",
      status: "proposed",
    },
    {
      id: "seed-2026-12-11",
      date: "2026-12-11",
      time: "15:30",
      topic: "20-minute research Presentation",
      speaker: "Harel",
      notes: "",
      status: "proposed",
    },
    {
      id: "seed-2026-12-18",
      date: "2026-12-18",
      time: "15:30",
      topic: "A presentation on the different philosophies of minds with a focus on AI. ",
      speaker: "Karl",
      notes: "Probably Karl given his undergraduate background. ",
      status: "proposed",
    },
  ],
  ideas: [
    {
      id: "seed-idea-ai-teaching",
      topic: "AI Assisted Teaching/ Research",
      suggestedSpeaker: "",
      notes: "",
      proposedDate: "",
      createdAt: "2026-09-01T03:24:48.618Z",
    },
    {
      id: "seed-idea-code",
      topic: "CODE",
      suggestedSpeaker: "Anyone or having multiple people would be nice to see different styles. ",
      notes: "A code review where someone shows their current code, and we discuss it (could be someone working on MBIRJAX or their own codebase). This meeting would allow others to see other coding practices, high level understand and things of that nature. ",
      proposedDate: "",
      createdAt: "2026-09-01T03:25:25.880Z",
    },
    {
      id: "seed-idea-ai-debate",
      topic: "AI",
      suggestedSpeaker: "",
      notes: "A debate on the future of AI, I think, would be really cool. I know some people are probably optimistic about it while others are pessimistic about it.  Probably need an informal survey to figure out who it optimistic and who is pessimistic. ",
      proposedDate: "",
      createdAt: "2026-09-01T03:26:00.000Z",
    },
  ],
};
